version: '3'
services:
  app:
    build: .
    container_name: rally
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - PORT=5001
    ports:
      - "5001:5001"